name: Feature
description: Plan a new feature or task
labels: ["feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should this issue achieve and why?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Concrete tasks as a checklist.
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this issue is done?
    validations:
      required: true
